export const prepItems = [
{
id: "prep-1",
name: "Diced Onions",
parLevel: 10,
onHand: 2,
targetQty: 8,
unit: "cup",
priority: 1,
status: "in_progress",
assignedTo: "Sam",
},
{
id: "prep-2",
name: "Shredded cheddar",
parLevel: 6,
onHand: 1,
targetQty: 5,
unit: "lb",
priority: 2,
status: "done",
assignedTo: "Ari",
},
{
id: "prep-3",
name: "Ranch dressing",
parLevel: 4,
onHand: 0,
targetQty: 4,
unit: "l",
priority: 1,
status: "done",
assignedTo: "Lee",
},
{
id: "prep-4",
name: "Tomato basil soup",
parLevel: 2,
onHand: 1,
targetQty: 1,
unit: "l",
priority: 3,
status: "done",
assignedTo: "Jordan",
},
{
id: "prep-5",
name: "House croutons",
parLevel: 3,
onHand: 0,
targetQty: 3,
unit: "pan",
priority: 2,
status: "todo",
assignedTo: "Unassigned",
},
];

export const recipes = [
{
id: "rec-1",
name: "Ranch Dressing",
category: "sauce",
ingredients: [
{ id: "ing-1", name: "Buttermilk", quantity: 2, unit: "cup" },
{ id: "ing-2", name: "Mayonnaise", quantity: 1, unit: "cup" },
{ id: "ing-3", name: "Ranch seasoning", quantity: 2, unit: "tbsp" },
],
steps: ["Whisk ingredients", "Chill 30 minutes", "Label and date"],
yieldAmount: 1.5,
yieldUnit: "l",
prepTimeMin: 10,
tags: ["cold prep"],
active: true,
createdAt: new Date().toISOString(),
updatedAt: new Date().toISOString(),
},
{
id: "rec-2",
name: "House Croutons",
category: "bakery",
ingredients: [
{ id: "ing-4", name: "Bread cubes", quantity: 1, unit: "tray" },
{ id: "ing-5", name: "Olive oil", quantity: 4, unit: "tbsp" },
{ id: "ing-6", name: "Seasoning blend", quantity: 2, unit: "tbsp" },
],
steps: ["Toss bread with oil and seasoning", "Bake until golden", "Cool"],
yieldAmount: 1,
yieldUnit: "tray",
prepTimeMin: 15,
cookTimeMin: 12,
tags: ["line"],
active: true,
createdAt: new Date().toISOString(),
updatedAt: new Date().toISOString(),
},
];

export const handovers = [
{
id: "handover-1",
businessDate: "2026-05-30",
shiftType: "pm",
fromUser: "Sam",
toUser: "Ari",
summary: "Dinner rush setup complete. Prioritize croutons and soup top-up.",
prepItems: [prepItems[0], prepItems[4]],
lowStockItems: [{ name: "Romaine", onHand: 2, unit: "lb" }],
issues: ["Oven 2 runs hot by ~15F"],
blockers: ["Need bread delivery before next crouton batch"],
signedOff: true,
createdAt: new Date().toISOString(),
updatedAt: new Date().toISOString(),
},
];